// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformPlatform.AccountManagement.Infrastructure;

#nullable disable

namespace PlatformPlatform.AccountManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AccountManagementDbContext))]
    [Migration("20240221000851_AddIdentityUserClaims")]
    partial class AddIdentityUserClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<PlatformPlatform.AccountManagement.Domain.Users.UserId>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("varchar(100)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(1014)");

                b.Property<string>("UserId")
                    .HasColumnType("varchar(26)");

                b.HasKey("Id");

                b.ToTable("IdentityUserClaims");
            });
#pragma warning restore 612, 618
        }
    }
}
